# Generated by Django 3.1.2 on 2020-10-09 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Собития', 'verbose_name_plural': 'Собития'},
        ),
    ]
